CREATE TABLE details (
first_name VARCHAR(15) NOTNULL
last_name VARCHAR(15)  NOTNULL
middle_name VARCHAR(15) NOTNULL
subject1  VARCHAR(15) NOTNULL
subject2  VARCHAR(15) NOTNULL
subject3  VARCHAR(15) NOTNULL
subject4  VARCHAR(15) NOTNULL
subject5  VARCHAR(15) NOTNULL
subject6  VARCHAR(15) NOTNULL
sex  VARCHAR(15) NOTNULL
);
